index:
    path: /
    controller: App\Controller\DefaultController

chuck:
  path: /chuck
  controller: App\Controller\ChuckController


Orders_list:
  path: /orders
  controller: App\Controller\OrdersList
  methods: ["GET"]


  Orders_detail:
    path: /orders/{id}
    controller: App\Controller\OrderDetail
    methods: ["GET"]